### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by Rotlocke1305** [FedUpWith-Tech/DynmapBlockScan-Data#14]
Hallo i know "Issues" is the wrong tab. But i dont know where i need to post it.

I used the BlockScan and get the .txts, and it works "ok". Some mods are showing, some are invisible and other textures are black.
For Example Create, i used my generated txt and it was invisible, but your works. I dont know why. I have some other mods like industrial foregoing who is  back. Or Mekanism is invisible. But i dont know why. 
I dont want to ask you how u make it work. (And i dont know how to pull requests). I want to try it by my own. 
Or i need to post the mods who are not workling in the official github of the DynmapBlockScan? 
Its all 1.18.2. 

Sry for this ultra bad english :)

Viele Grüße
Rotlocke1305

**Comment by Cobbert** [comment]
All I did was run the block scanner on my modded server (ATM7) and after it scanned it all, stopped the server, copied all files from dynmap/rednerdata/modsupport to dynmap/renderdata, deleted the block scanner plugin, started the server, and ran fullrender for all worlds and it slowly re-rendered with almost all textures, I think a few are none standard stuff that was changed for ATM7 though.

**Comment by Rotlocke1305** [comment]
I did it too but the same issue.
Now i testet it for industrial foregoing local. Only this mod, Dynmap and BlockScan. It worked, i dont know why. I copied the files in renderdata on my server and now its working there too. 
But i did the same on my server. Maybe BlockScan cant handle to much mods at the same time if he generate the txts. I doing it now for every mod.

**Comment by Cobbert** [comment]
I ran mine on the server, game version 18.3, mod was three different mods packs including atm7, direwolf, and plexiglass mountain, all worked just fine, though I did see some errors in the console on start up.

I'm sorry I can be more help, but if you like I can try to generate the files for the mod pack you are using and see if that works?

Aug 22, 2022 5:54:01 AM Rotlocke1305 ***@***.***>:

**Comment by Rotlocke1305** [comment]
It worked fine now too. I dont know why it has these bugs at my first start. 

only few blocks are not working, Industrial Craft Multiblocks, Mekanism, AE Cables. Wind/Solar-Generators (Mekanism). Bonsai Trees.
But the most are working.

Is it possible to show Cables or Multiblocks? If i change the "transparency" it does nothing exept lightning :)

For example i saw in the mekanismgenerators-texture.txt is no texture:id for the windgenerator. I try to add : "texture:id=wind_generator,filename=assets/mekanismgenerators/textures/block/model/windt_generator.png,xcount=1,ycount=1" and look what it does.

"block:id=%wind_generator,state=facing:north,transparency=TRANSPARENT,stdrot=true" is in the txt

**Comment by Rotlocke1305** [comment]
Im glad that u try to help me :)
Its my first server with dynmap.
Add the line to the txt does nothing but i will test more the next days. 

Argh i dont mean Industrial Craft Multiblocks...... its Immersive Engineering.
ATM7 has the most mods :)

**Comment by Rotlocke1305** [comment]
![Immersive](https://user-images.githubusercontent.com/110396827/185959771-c7162037-66f2-4abb-9050-255b8cbd8254.PNG)

Its a 3x3x3 Coke-Brick Block. next to him is the same but as Oven. U can see the tank. Above the tank is the IE fluid pump. Invisible too :/. Maybe u can test it on your server.

**Comment by Rotlocke1305** [comment]
I found this:

https://www.reddit.com/r/feedthebeast/comments/bwa5q6/how_to_dynmap_mod_textures/

i will test it, and if it workes i can create modified txts. I dont think it works with Multiblocks, but with "normal" blocks.
